#!/usr/bin/env bash

#
# @author weichangjun
# @version 1.0.0
# @since 2025/04/04
#

echo "Running $ mvn checkstyle:check ..."
mvn checkstyle:check

if [ $? -ne 0 ]; then
    echo "Checkstyle failed. Commit aborted."
    exit 1
fi

echo "Checkstyle passed. Proceeding with commit..."
exit 0
